version: '3.7'
services:
  fog:
    build:
      context: .
      args:
        #FOG version to be installed
        FOG_VERSION: 1.5.10
    volumes:
      - ./images:/images
      - ./database:/var/lib/mysql
    ports:
      - 8080:80
